# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astarteplatform/msghub/interface.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&astarteplatform/msghub/interface.proto\x12\x16\x61starteplatform.msghub\")\n\x0eInterfacesJson\x12\x17\n\x0finterfaces_json\x18\x01 \x03(\t\"\x1f\n\x0eInterfacesName\x12\r\n\x05names\x18\x01 \x03(\t*#\n\tOwnership\x12\n\n\x06\x44\x45VICE\x10\x00\x12\n\n\x06SERVER\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astarteplatform.msghub.interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OWNERSHIP']._serialized_start=142
  _globals['_OWNERSHIP']._serialized_end=177
  _globals['_INTERFACESJSON']._serialized_start=66
  _globals['_INTERFACESJSON']._serialized_end=107
  _globals['_INTERFACESNAME']._serialized_start=109
  _globals['_INTERFACESNAME']._serialized_end=140
# @@protoc_insertion_point(module_scope)
