# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astarteplatform/msghub/message_hub_error.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.astarteplatform/msghub/message_hub_error.proto\x12\x16\x61starteplatform.msghub\"\xd4\x01\n\x0fMessageHubError\x12\x45\n\nerror_code\x18\x01 \x01(\x0e\x32\x31.astarteplatform.msghub.MessageHubError.ErrorCode\x12\x19\n\x11\x65rror_description\x18\x02 \x01(\t\"_\n\tErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x18\n\x14\x41STARTE_INVALID_DATA\x10\x01\x12\x15\n\x11\x41STARTE_SDK_ERROR\x10\x02\x12\x14\n\x10\x43ONVERSION_ERROR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astarteplatform.msghub.message_hub_error_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEHUBERROR']._serialized_start=75
  _globals['_MESSAGEHUBERROR']._serialized_end=287
  _globals['_MESSAGEHUBERROR_ERRORCODE']._serialized_start=192
  _globals['_MESSAGEHUBERROR_ERRORCODE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
