# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from astarteplatform.msghub import astarte_message_pb2 as astarteplatform_dot_msghub_dot_astarte__message__pb2
from astarteplatform.msghub import interface_pb2 as astarteplatform_dot_msghub_dot_interface__pb2
from astarteplatform.msghub import node_pb2 as astarteplatform_dot_msghub_dot_node__pb2
from astarteplatform.msghub import property_pb2 as astarteplatform_dot_msghub_dot_property__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MessageHubStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Attach = channel.unary_stream(
                '/astarteplatform.msghub.MessageHub/Attach',
                request_serializer=astarteplatform_dot_msghub_dot_node__pb2.Node.SerializeToString,
                response_deserializer=astarteplatform_dot_msghub_dot_astarte__message__pb2.MessageHubEvent.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/astarteplatform.msghub.MessageHub/Send',
                request_serializer=astarteplatform_dot_msghub_dot_astarte__message__pb2.AstarteMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Detach = channel.unary_unary(
                '/astarteplatform.msghub.MessageHub/Detach',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddInterfaces = channel.unary_unary(
                '/astarteplatform.msghub.MessageHub/AddInterfaces',
                request_serializer=astarteplatform_dot_msghub_dot_interface__pb2.InterfacesJson.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveInterfaces = channel.unary_unary(
                '/astarteplatform.msghub.MessageHub/RemoveInterfaces',
                request_serializer=astarteplatform_dot_msghub_dot_interface__pb2.InterfacesName.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetProperties = channel.unary_unary(
                '/astarteplatform.msghub.MessageHub/GetProperties',
                request_serializer=astarteplatform_dot_msghub_dot_interface__pb2.InterfacesName.SerializeToString,
                response_deserializer=astarteplatform_dot_msghub_dot_property__pb2.StoredProperties.FromString,
                _registered_method=True)
        self.GetAllProperties = channel.unary_unary(
                '/astarteplatform.msghub.MessageHub/GetAllProperties',
                request_serializer=astarteplatform_dot_msghub_dot_property__pb2.StoredPropertiesFilter.SerializeToString,
                response_deserializer=astarteplatform_dot_msghub_dot_property__pb2.StoredProperties.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/astarteplatform.msghub.MessageHub/GetProperty',
                request_serializer=astarteplatform_dot_msghub_dot_property__pb2.PropertyIdentifier.SerializeToString,
                response_deserializer=astarteplatform_dot_msghub_dot_property__pb2.Property.FromString,
                _registered_method=True)


class MessageHubServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Attach(self, request, context):
        """This function should be used to attach a node to an instance of the Astarte message hub.
        Returns a data stream from the Astarte message hub.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """This function should be used to send an `AstarteMessage` to Astarte. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detach(self, request, context):
        """This function should be used to detach a node from an instance of the Astarte message hub. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddInterfaces(self, request, context):
        """This function should be used to add one or more interfaces to an instance of the Astarte message hub. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveInterfaces(self, request, context):
        """This function should be used to remove one or more interfaces from an instance of the Astarte message hub. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperties(self, request, context):
        """Get properties associated with the passed interfaces. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllProperties(self, request, context):
        """Get all the properties, allowing also filtering by interface ownership. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Get a specific property by its identifier, could be an unset property  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Attach': grpc.unary_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=astarteplatform_dot_msghub_dot_node__pb2.Node.FromString,
                    response_serializer=astarteplatform_dot_msghub_dot_astarte__message__pb2.MessageHubEvent.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=astarteplatform_dot_msghub_dot_astarte__message__pb2.AstarteMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Detach': grpc.unary_unary_rpc_method_handler(
                    servicer.Detach,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.AddInterfaces,
                    request_deserializer=astarteplatform_dot_msghub_dot_interface__pb2.InterfacesJson.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveInterfaces,
                    request_deserializer=astarteplatform_dot_msghub_dot_interface__pb2.InterfacesName.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperties,
                    request_deserializer=astarteplatform_dot_msghub_dot_interface__pb2.InterfacesName.FromString,
                    response_serializer=astarteplatform_dot_msghub_dot_property__pb2.StoredProperties.SerializeToString,
            ),
            'GetAllProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllProperties,
                    request_deserializer=astarteplatform_dot_msghub_dot_property__pb2.StoredPropertiesFilter.FromString,
                    response_serializer=astarteplatform_dot_msghub_dot_property__pb2.StoredProperties.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=astarteplatform_dot_msghub_dot_property__pb2.PropertyIdentifier.FromString,
                    response_serializer=astarteplatform_dot_msghub_dot_property__pb2.Property.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astarteplatform.msghub.MessageHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astarteplatform.msghub.MessageHub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageHub(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Attach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/Attach',
            astarteplatform_dot_msghub_dot_node__pb2.Node.SerializeToString,
            astarteplatform_dot_msghub_dot_astarte__message__pb2.MessageHubEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/Send',
            astarteplatform_dot_msghub_dot_astarte__message__pb2.AstarteMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/Detach',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/AddInterfaces',
            astarteplatform_dot_msghub_dot_interface__pb2.InterfacesJson.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/RemoveInterfaces',
            astarteplatform_dot_msghub_dot_interface__pb2.InterfacesName.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/GetProperties',
            astarteplatform_dot_msghub_dot_interface__pb2.InterfacesName.SerializeToString,
            astarteplatform_dot_msghub_dot_property__pb2.StoredProperties.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/GetAllProperties',
            astarteplatform_dot_msghub_dot_property__pb2.StoredPropertiesFilter.SerializeToString,
            astarteplatform_dot_msghub_dot_property__pb2.StoredProperties.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astarteplatform.msghub.MessageHub/GetProperty',
            astarteplatform_dot_msghub_dot_property__pb2.PropertyIdentifier.SerializeToString,
            astarteplatform_dot_msghub_dot_property__pb2.Property.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
