# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astarteplatform/msghub/node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from astarteplatform.msghub import astarte_message_pb2 as astarteplatform_dot_msghub_dot_astarte__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!astarteplatform/msghub/node.proto\x12\x16\x61starteplatform.msghub\x1a,astarteplatform/msghub/astarte_message.proto\"-\n\x04Node\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x17\n\x0finterface_jsons\x18\x02 \x03(\x0c\"\\\n\x0bNodeMessage\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12?\n\x0f\x61starte_message\x18\x02 \x01(\x0b\x32&.astarteplatform.msghub.AstarteMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astarteplatform.msghub.node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NODE']._serialized_start=107
  _globals['_NODE']._serialized_end=152
  _globals['_NODEMESSAGE']._serialized_start=154
  _globals['_NODEMESSAGE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
