// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: astarteplatform/msghub/message_hub_error.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_astarteplatform_2fmsghub_2fmessage_5fhub_5ferror_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_astarteplatform_2fmsghub_2fmessage_5fhub_5ferror_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_astarteplatform_2fmsghub_2fmessage_5fhub_5ferror_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_astarteplatform_2fmsghub_2fmessage_5fhub_5ferror_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_astarteplatform_2fmsghub_2fmessage_5fhub_5ferror_2eproto;
namespace astarteplatform {
namespace msghub {
class MessageHubError;
struct MessageHubErrorDefaultTypeInternal;
extern MessageHubErrorDefaultTypeInternal _MessageHubError_default_instance_;
}  // namespace msghub
}  // namespace astarteplatform
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace astarteplatform {
namespace msghub {

// ===================================================================


// -------------------------------------------------------------------

class MessageHubError final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:astarteplatform.msghub.MessageHubError) */ {
 public:
  inline MessageHubError() : MessageHubError(nullptr) {}
  ~MessageHubError() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MessageHubError(
      ::google::protobuf::internal::ConstantInitialized);

  inline MessageHubError(const MessageHubError& from) : MessageHubError(nullptr, from) {}
  inline MessageHubError(MessageHubError&& from) noexcept
      : MessageHubError(nullptr, std::move(from)) {}
  inline MessageHubError& operator=(const MessageHubError& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageHubError& operator=(MessageHubError&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageHubError& default_instance() {
    return *internal_default_instance();
  }
  static inline const MessageHubError* internal_default_instance() {
    return reinterpret_cast<const MessageHubError*>(
        &_MessageHubError_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MessageHubError& a, MessageHubError& b) { a.Swap(&b); }
  inline void Swap(MessageHubError* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageHubError* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageHubError* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<MessageHubError>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageHubError& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageHubError& from) { MessageHubError::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MessageHubError* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "astarteplatform.msghub.MessageHubError"; }

 protected:
  explicit MessageHubError(::google::protobuf::Arena* arena);
  MessageHubError(::google::protobuf::Arena* arena, const MessageHubError& from);
  MessageHubError(::google::protobuf::Arena* arena, MessageHubError&& from) noexcept
      : MessageHubError(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSourceFieldNumber = 2,
    kDescriptionFieldNumber = 1,
  };
  // repeated string source = 2;
  int source_size() const;
  private:
  int _internal_source_size() const;

  public:
  void clear_source() ;
  const std::string& source(int index) const;
  std::string* mutable_source(int index);
  void set_source(int index, const std::string& value);
  void set_source(int index, std::string&& value);
  void set_source(int index, const char* value);
  void set_source(int index, const char* value, std::size_t size);
  void set_source(int index, absl::string_view value);
  std::string* add_source();
  void add_source(const std::string& value);
  void add_source(std::string&& value);
  void add_source(const char* value);
  void add_source(const char* value, std::size_t size);
  void add_source(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& source() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_source();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_source() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_source();

  public:
  // string description = 1;
  void clear_description() ;
  const std::string& description() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_description(Arg_&& arg, Args_... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* value);

  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(
      const std::string& value);
  std::string* _internal_mutable_description();

  public:
  // @@protoc_insertion_point(class_scope:astarteplatform.msghub.MessageHubError)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      64, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MessageHubError_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MessageHubError& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> source_;
    ::google::protobuf::internal::ArenaStringPtr description_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_astarteplatform_2fmsghub_2fmessage_5fhub_5ferror_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MessageHubError

// string description = 1;
inline void MessageHubError::clear_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_.ClearToEmpty();
}
inline const std::string& MessageHubError::description() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:astarteplatform.msghub.MessageHubError.description)
  return _internal_description();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MessageHubError::set_description(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:astarteplatform.msghub.MessageHubError.description)
}
inline std::string* MessageHubError::mutable_description() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:astarteplatform.msghub.MessageHubError.description)
  return _s;
}
inline const std::string& MessageHubError::_internal_description() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.description_.Get();
}
inline void MessageHubError::_internal_set_description(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_.Set(value, GetArena());
}
inline std::string* MessageHubError::_internal_mutable_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.description_.Mutable( GetArena());
}
inline std::string* MessageHubError::release_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:astarteplatform.msghub.MessageHubError.description)
  return _impl_.description_.Release();
}
inline void MessageHubError::set_allocated_description(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.description_.IsDefault()) {
          _impl_.description_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:astarteplatform.msghub.MessageHubError.description)
}

// repeated string source = 2;
inline int MessageHubError::_internal_source_size() const {
  return _internal_source().size();
}
inline int MessageHubError::source_size() const {
  return _internal_source_size();
}
inline void MessageHubError::clear_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_.Clear();
}
inline std::string* MessageHubError::add_source()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_source()->Add();
  // @@protoc_insertion_point(field_add_mutable:astarteplatform.msghub.MessageHubError.source)
  return _s;
}
inline const std::string& MessageHubError::source(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:astarteplatform.msghub.MessageHubError.source)
  return _internal_source().Get(index);
}
inline std::string* MessageHubError::mutable_source(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:astarteplatform.msghub.MessageHubError.source)
  return _internal_mutable_source()->Mutable(index);
}
inline void MessageHubError::set_source(int index, const std::string& value) {
  _internal_mutable_source()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::set_source(int index, std::string&& value) {
  _internal_mutable_source()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::set_source(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_source()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::set_source(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_source()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::set_source(int index, absl::string_view value) {
  _internal_mutable_source()->Mutable(index)->assign(
      value.data(), value.size());
  // @@protoc_insertion_point(field_set_string_piece:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::add_source(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_source()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::add_source(std::string&& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_source()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::add_source(const char* value) {
  ABSL_DCHECK(value != nullptr);
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_source()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::add_source(const char* value, std::size_t size) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_source()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:astarteplatform.msghub.MessageHubError.source)
}
inline void MessageHubError::add_source(absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_source()->Add()->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_add_string_piece:astarteplatform.msghub.MessageHubError.source)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
MessageHubError::source() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:astarteplatform.msghub.MessageHubError.source)
  return _internal_source();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
MessageHubError::mutable_source() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:astarteplatform.msghub.MessageHubError.source)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_source();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
MessageHubError::_internal_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
MessageHubError::_internal_mutable_source() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.source_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace msghub
}  // namespace astarteplatform


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_astarteplatform_2fmsghub_2fmessage_5fhub_5ferror_2eproto_2epb_2eh
