// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: astarteplatform/msghub/property.proto
// Protobuf C++ Version: 5.29.0

#include "astarteplatform/msghub/property.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace astarteplatform {
namespace msghub {

inline constexpr StoredPropertiesFilter::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ownership_{static_cast< ::astarteplatform::msghub::Ownership >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR StoredPropertiesFilter::StoredPropertiesFilter(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StoredPropertiesFilterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StoredPropertiesFilterDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StoredPropertiesFilterDefaultTypeInternal() {}
  union {
    StoredPropertiesFilter _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StoredPropertiesFilterDefaultTypeInternal _StoredPropertiesFilter_default_instance_;

inline constexpr PropertyIdentifier::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : interface_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PropertyIdentifier::PropertyIdentifier(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PropertyIdentifierDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PropertyIdentifierDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PropertyIdentifierDefaultTypeInternal() {}
  union {
    PropertyIdentifier _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PropertyIdentifierDefaultTypeInternal _PropertyIdentifier_default_instance_;

inline constexpr Property::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Property::Property(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PropertyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PropertyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PropertyDefaultTypeInternal() {}
  union {
    Property _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PropertyDefaultTypeInternal _Property_default_instance_;

inline constexpr InterfaceProperties::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : properties_{},
        ownership_{static_cast< ::astarteplatform::msghub::Ownership >(0)},
        version_major_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InterfaceProperties::InterfaceProperties(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InterfacePropertiesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InterfacePropertiesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InterfacePropertiesDefaultTypeInternal() {}
  union {
    InterfaceProperties _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InterfacePropertiesDefaultTypeInternal _InterfaceProperties_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR StoredProperties_InterfacePropertiesEntry_DoNotUse::StoredProperties_InterfacePropertiesEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : StoredProperties_InterfacePropertiesEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : StoredProperties_InterfacePropertiesEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct StoredProperties_InterfacePropertiesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StoredProperties_InterfacePropertiesEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StoredProperties_InterfacePropertiesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    StoredProperties_InterfacePropertiesEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StoredProperties_InterfacePropertiesEntry_DoNotUseDefaultTypeInternal _StoredProperties_InterfacePropertiesEntry_DoNotUse_default_instance_;

inline constexpr StoredProperties::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : interface_properties_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StoredProperties::StoredProperties(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StoredPropertiesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StoredPropertiesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StoredPropertiesDefaultTypeInternal() {}
  union {
    StoredProperties _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StoredPropertiesDefaultTypeInternal _StoredProperties_default_instance_;
}  // namespace msghub
}  // namespace astarteplatform
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_astarteplatform_2fmsghub_2fproperty_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_astarteplatform_2fmsghub_2fproperty_2eproto = nullptr;
const ::uint32_t
    TableStruct_astarteplatform_2fmsghub_2fproperty_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::Property, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::Property, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::Property, _impl_.path_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::Property, _impl_.data_),
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::InterfaceProperties, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::InterfaceProperties, _impl_.ownership_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::InterfaceProperties, _impl_.version_major_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::InterfaceProperties, _impl_.properties_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredProperties_InterfacePropertiesEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredProperties, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredProperties, _impl_.interface_properties_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredPropertiesFilter, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredPropertiesFilter, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::StoredPropertiesFilter, _impl_.ownership_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::PropertyIdentifier, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::PropertyIdentifier, _impl_.interface_name_),
        PROTOBUF_FIELD_OFFSET(::astarteplatform::msghub::PropertyIdentifier, _impl_.path_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::astarteplatform::msghub::Property)},
        {12, -1, -1, sizeof(::astarteplatform::msghub::InterfaceProperties)},
        {23, 33, -1, sizeof(::astarteplatform::msghub::StoredProperties_InterfacePropertiesEntry_DoNotUse)},
        {35, -1, -1, sizeof(::astarteplatform::msghub::StoredProperties)},
        {44, 53, -1, sizeof(::astarteplatform::msghub::StoredPropertiesFilter)},
        {54, -1, -1, sizeof(::astarteplatform::msghub::PropertyIdentifier)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::astarteplatform::msghub::_Property_default_instance_._instance,
    &::astarteplatform::msghub::_InterfaceProperties_default_instance_._instance,
    &::astarteplatform::msghub::_StoredProperties_InterfacePropertiesEntry_DoNotUse_default_instance_._instance,
    &::astarteplatform::msghub::_StoredProperties_default_instance_._instance,
    &::astarteplatform::msghub::_StoredPropertiesFilter_default_instance_._instance,
    &::astarteplatform::msghub::_PropertyIdentifier_default_instance_._instance,
};
const char descriptor_table_protodef_astarteplatform_2fmsghub_2fproperty_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n%astarteplatform/msghub/property.proto\022"
    "\026astarteplatform.msghub\032)astarteplatform"
    "/msghub/astarte_data.proto\032&astarteplatf"
    "orm/msghub/interface.proto\"Y\n\010Property\022\014"
    "\n\004path\030\001 \001(\t\0226\n\004data\030\002 \001(\0132#.astarteplat"
    "form.msghub.AstarteDataH\000\210\001\001B\007\n\005_data\"\230\001"
    "\n\023InterfaceProperties\0224\n\townership\030\001 \001(\016"
    "2!.astarteplatform.msghub.Ownership\022\025\n\rv"
    "ersion_major\030\002 \001(\005\0224\n\nproperties\030\003 \003(\0132 "
    ".astarteplatform.msghub.Property\"\334\001\n\020Sto"
    "redProperties\022_\n\024interface_properties\030\001 "
    "\003(\0132A.astarteplatform.msghub.StoredPrope"
    "rties.InterfacePropertiesEntry\032g\n\030Interf"
    "acePropertiesEntry\022\013\n\003key\030\001 \001(\t\022:\n\005value"
    "\030\002 \001(\0132+.astarteplatform.msghub.Interfac"
    "eProperties:\0028\001\"a\n\026StoredPropertiesFilte"
    "r\0229\n\townership\030\001 \001(\0162!.astarteplatform.m"
    "sghub.OwnershipH\000\210\001\001B\014\n\n_ownership\":\n\022Pr"
    "opertyIdentifier\022\026\n\016interface_name\030\001 \001(\t"
    "\022\014\n\004path\030\002 \001(\tb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto_deps[2] =
    {
        &::descriptor_table_astarteplatform_2fmsghub_2fastarte_5fdata_2eproto,
        &::descriptor_table_astarteplatform_2fmsghub_2finterface_2eproto,
};
static ::absl::once_flag descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto = {
    false,
    false,
    782,
    descriptor_table_protodef_astarteplatform_2fmsghub_2fproperty_2eproto,
    "astarteplatform/msghub/property.proto",
    &descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto_once,
    descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto_deps,
    2,
    6,
    schemas,
    file_default_instances,
    TableStruct_astarteplatform_2fmsghub_2fproperty_2eproto::offsets,
    file_level_enum_descriptors_astarteplatform_2fmsghub_2fproperty_2eproto,
    file_level_service_descriptors_astarteplatform_2fmsghub_2fproperty_2eproto,
};
namespace astarteplatform {
namespace msghub {
// ===================================================================

class Property::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Property>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Property, _impl_._has_bits_);
};

void Property::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Property::Property(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:astarteplatform.msghub.Property)
}
inline PROTOBUF_NDEBUG_INLINE Property::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::astarteplatform::msghub::Property& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        path_(arena, from.path_) {}

Property::Property(
    ::google::protobuf::Arena* arena,
    const Property& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Property* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.data_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::astarteplatform::msghub::AstarteData>(
                              arena, *from._impl_.data_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:astarteplatform.msghub.Property)
}
inline PROTOBUF_NDEBUG_INLINE Property::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        path_(arena) {}

inline void Property::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.data_ = {};
}
Property::~Property() {
  // @@protoc_insertion_point(destructor:astarteplatform.msghub.Property)
  SharedDtor(*this);
}
inline void Property::SharedDtor(MessageLite& self) {
  Property& this_ = static_cast<Property&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.path_.Destroy();
  delete this_._impl_.data_;
  this_._impl_.~Impl_();
}

inline void* Property::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Property(arena);
}
constexpr auto Property::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Property),
                                            alignof(Property));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Property::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Property_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Property::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Property>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Property::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Property>(), &Property::ByteSizeLong,
            &Property::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Property, _impl_._cached_size_),
        false,
    },
    &Property::kDescriptorMethods,
    &descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Property::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 44, 2> Property::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Property, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::astarteplatform::msghub::Property>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .astarteplatform.msghub.AstarteData data = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Property, _impl_.data_)}},
    // string path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Property, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string path = 1;
    {PROTOBUF_FIELD_OFFSET(Property, _impl_.path_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .astarteplatform.msghub.AstarteData data = 2;
    {PROTOBUF_FIELD_OFFSET(Property, _impl_.data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::astarteplatform::msghub::AstarteData>()},
  }}, {{
    "\37\4\0\0\0\0\0\0"
    "astarteplatform.msghub.Property"
    "path"
  }},
};

PROTOBUF_NOINLINE void Property::Clear() {
// @@protoc_insertion_point(message_clear_start:astarteplatform.msghub.Property)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.data_ != nullptr);
    _impl_.data_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Property::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Property& this_ = static_cast<const Property&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Property::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Property& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:astarteplatform.msghub.Property)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string path = 1;
          if (!this_._internal_path().empty()) {
            const std::string& _s = this_._internal_path();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "astarteplatform.msghub.Property.path");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .astarteplatform.msghub.AstarteData data = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.data_, this_._impl_.data_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:astarteplatform.msghub.Property)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Property::ByteSizeLong(const MessageLite& base) {
          const Property& this_ = static_cast<const Property&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Property::ByteSizeLong() const {
          const Property& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:astarteplatform.msghub.Property)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string path = 1;
            if (!this_._internal_path().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_path());
            }
          }
           {
            // optional .astarteplatform.msghub.AstarteData data = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.data_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Property::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Property*>(&to_msg);
  auto& from = static_cast<const Property&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:astarteplatform.msghub.Property)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.data_ != nullptr);
    if (_this->_impl_.data_ == nullptr) {
      _this->_impl_.data_ =
          ::google::protobuf::Message::CopyConstruct<::astarteplatform::msghub::AstarteData>(arena, *from._impl_.data_);
    } else {
      _this->_impl_.data_->MergeFrom(*from._impl_.data_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Property::CopyFrom(const Property& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:astarteplatform.msghub.Property)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Property::InternalSwap(Property* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
  swap(_impl_.data_, other->_impl_.data_);
}

::google::protobuf::Metadata Property::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InterfaceProperties::_Internal {
 public:
};

InterfaceProperties::InterfaceProperties(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:astarteplatform.msghub.InterfaceProperties)
}
inline PROTOBUF_NDEBUG_INLINE InterfaceProperties::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::astarteplatform::msghub::InterfaceProperties& from_msg)
      : properties_{visibility, arena, from.properties_},
        _cached_size_{0} {}

InterfaceProperties::InterfaceProperties(
    ::google::protobuf::Arena* arena,
    const InterfaceProperties& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InterfaceProperties* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ownership_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, ownership_),
           offsetof(Impl_, version_major_) -
               offsetof(Impl_, ownership_) +
               sizeof(Impl_::version_major_));

  // @@protoc_insertion_point(copy_constructor:astarteplatform.msghub.InterfaceProperties)
}
inline PROTOBUF_NDEBUG_INLINE InterfaceProperties::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : properties_{visibility, arena},
        _cached_size_{0} {}

inline void InterfaceProperties::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ownership_),
           0,
           offsetof(Impl_, version_major_) -
               offsetof(Impl_, ownership_) +
               sizeof(Impl_::version_major_));
}
InterfaceProperties::~InterfaceProperties() {
  // @@protoc_insertion_point(destructor:astarteplatform.msghub.InterfaceProperties)
  SharedDtor(*this);
}
inline void InterfaceProperties::SharedDtor(MessageLite& self) {
  InterfaceProperties& this_ = static_cast<InterfaceProperties&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* InterfaceProperties::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InterfaceProperties(arena);
}
constexpr auto InterfaceProperties::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.properties_) +
          decltype(InterfaceProperties::_impl_.properties_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(InterfaceProperties), alignof(InterfaceProperties), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&InterfaceProperties::PlacementNew_,
                                 sizeof(InterfaceProperties),
                                 alignof(InterfaceProperties));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InterfaceProperties::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InterfaceProperties_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InterfaceProperties::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InterfaceProperties>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InterfaceProperties::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InterfaceProperties>(), &InterfaceProperties::ByteSizeLong,
            &InterfaceProperties::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_._cached_size_),
        false,
    },
    &InterfaceProperties::kDescriptorMethods,
    &descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InterfaceProperties::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> InterfaceProperties::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::astarteplatform::msghub::InterfaceProperties>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .astarteplatform.msghub.Ownership ownership = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InterfaceProperties, _impl_.ownership_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.ownership_)}},
    // int32 version_major = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InterfaceProperties, _impl_.version_major_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.version_major_)}},
    // repeated .astarteplatform.msghub.Property properties = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.properties_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .astarteplatform.msghub.Ownership ownership = 1;
    {PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.ownership_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 version_major = 2;
    {PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.version_major_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .astarteplatform.msghub.Property properties = 3;
    {PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.properties_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::astarteplatform::msghub::Property>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void InterfaceProperties::Clear() {
// @@protoc_insertion_point(message_clear_start:astarteplatform.msghub.InterfaceProperties)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.properties_.Clear();
  ::memset(&_impl_.ownership_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.version_major_) -
      reinterpret_cast<char*>(&_impl_.ownership_)) + sizeof(_impl_.version_major_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InterfaceProperties::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InterfaceProperties& this_ = static_cast<const InterfaceProperties&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InterfaceProperties::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InterfaceProperties& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:astarteplatform.msghub.InterfaceProperties)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .astarteplatform.msghub.Ownership ownership = 1;
          if (this_._internal_ownership() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_ownership(), target);
          }

          // int32 version_major = 2;
          if (this_._internal_version_major() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_version_major(), target);
          }

          // repeated .astarteplatform.msghub.Property properties = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_properties_size());
               i < n; i++) {
            const auto& repfield = this_._internal_properties().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:astarteplatform.msghub.InterfaceProperties)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InterfaceProperties::ByteSizeLong(const MessageLite& base) {
          const InterfaceProperties& this_ = static_cast<const InterfaceProperties&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InterfaceProperties::ByteSizeLong() const {
          const InterfaceProperties& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:astarteplatform.msghub.InterfaceProperties)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .astarteplatform.msghub.Property properties = 3;
            {
              total_size += 1UL * this_._internal_properties_size();
              for (const auto& msg : this_._internal_properties()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // .astarteplatform.msghub.Ownership ownership = 1;
            if (this_._internal_ownership() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_ownership());
            }
            // int32 version_major = 2;
            if (this_._internal_version_major() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_version_major());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InterfaceProperties::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InterfaceProperties*>(&to_msg);
  auto& from = static_cast<const InterfaceProperties&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:astarteplatform.msghub.InterfaceProperties)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_properties()->MergeFrom(
      from._internal_properties());
  if (from._internal_ownership() != 0) {
    _this->_impl_.ownership_ = from._impl_.ownership_;
  }
  if (from._internal_version_major() != 0) {
    _this->_impl_.version_major_ = from._impl_.version_major_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InterfaceProperties::CopyFrom(const InterfaceProperties& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:astarteplatform.msghub.InterfaceProperties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InterfaceProperties::InternalSwap(InterfaceProperties* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.properties_.InternalSwap(&other->_impl_.properties_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.version_major_)
      + sizeof(InterfaceProperties::_impl_.version_major_)
      - PROTOBUF_FIELD_OFFSET(InterfaceProperties, _impl_.ownership_)>(
          reinterpret_cast<char*>(&_impl_.ownership_),
          reinterpret_cast<char*>(&other->_impl_.ownership_));
}

::google::protobuf::Metadata InterfaceProperties::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              StoredProperties_InterfacePropertiesEntry_DoNotUse::StoredProperties_InterfacePropertiesEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              StoredProperties_InterfacePropertiesEntry_DoNotUse::StoredProperties_InterfacePropertiesEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              StoredProperties_InterfacePropertiesEntry_DoNotUse::StoredProperties_InterfacePropertiesEntry_DoNotUse() : SuperType() {}
              StoredProperties_InterfacePropertiesEntry_DoNotUse::StoredProperties_InterfacePropertiesEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* StoredProperties_InterfacePropertiesEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) StoredProperties_InterfacePropertiesEntry_DoNotUse(arena);
              }
              constexpr auto StoredProperties_InterfacePropertiesEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(StoredProperties_InterfacePropertiesEntry_DoNotUse),
                                                          alignof(StoredProperties_InterfacePropertiesEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull StoredProperties_InterfacePropertiesEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_StoredProperties_InterfacePropertiesEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &StoredProperties_InterfacePropertiesEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<StoredProperties_InterfacePropertiesEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &StoredProperties_InterfacePropertiesEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &StoredProperties_InterfacePropertiesEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &StoredProperties_InterfacePropertiesEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* StoredProperties_InterfacePropertiesEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 76, 2> StoredProperties_InterfacePropertiesEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::astarteplatform::msghub::StoredProperties_InterfacePropertiesEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .astarteplatform.msghub.InterfaceProperties value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .astarteplatform.msghub.InterfaceProperties value = 2;
    {PROTOBUF_FIELD_OFFSET(StoredProperties_InterfacePropertiesEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::astarteplatform::msghub::InterfaceProperties>()},
  }}, {{
    "\100\3\0\0\0\0\0\0"
    "astarteplatform.msghub.StoredProperties.InterfacePropertiesEntry"
    "key"
  }},
};

// ===================================================================

class StoredProperties::_Internal {
 public:
};

StoredProperties::StoredProperties(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:astarteplatform.msghub.StoredProperties)
}
inline PROTOBUF_NDEBUG_INLINE StoredProperties::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::astarteplatform::msghub::StoredProperties& from_msg)
      : interface_properties_{visibility, arena, from.interface_properties_},
        _cached_size_{0} {}

StoredProperties::StoredProperties(
    ::google::protobuf::Arena* arena,
    const StoredProperties& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StoredProperties* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:astarteplatform.msghub.StoredProperties)
}
inline PROTOBUF_NDEBUG_INLINE StoredProperties::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : interface_properties_{visibility, arena},
        _cached_size_{0} {}

inline void StoredProperties::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
StoredProperties::~StoredProperties() {
  // @@protoc_insertion_point(destructor:astarteplatform.msghub.StoredProperties)
  SharedDtor(*this);
}
inline void StoredProperties::SharedDtor(MessageLite& self) {
  StoredProperties& this_ = static_cast<StoredProperties&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* StoredProperties::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StoredProperties(arena);
}
constexpr auto StoredProperties::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(StoredProperties, _impl_.interface_properties_) +
          decltype(StoredProperties::_impl_.interface_properties_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(StoredProperties, _impl_.interface_properties_) +
          decltype(StoredProperties::_impl_.interface_properties_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(StoredProperties), alignof(StoredProperties), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&StoredProperties::PlacementNew_,
                                 sizeof(StoredProperties),
                                 alignof(StoredProperties));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StoredProperties::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StoredProperties_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StoredProperties::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StoredProperties>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StoredProperties::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StoredProperties>(), &StoredProperties::ByteSizeLong,
            &StoredProperties::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StoredProperties, _impl_._cached_size_),
        false,
    },
    &StoredProperties::kDescriptorMethods,
    &descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StoredProperties::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 68, 2> StoredProperties::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::astarteplatform::msghub::StoredProperties>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, .astarteplatform.msghub.InterfaceProperties> interface_properties = 1;
    {PROTOBUF_FIELD_OFFSET(StoredProperties, _impl_.interface_properties_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(StoredProperties()._impl_.interface_properties_)>(
        1, 0, 0, 9,
        11)},
    {::_pbi::TcParser::GetTable<::astarteplatform::msghub::InterfaceProperties>()},
  }}, {{
    "\47\24\0\0\0\0\0\0"
    "astarteplatform.msghub.StoredProperties"
    "interface_properties"
  }},
};

PROTOBUF_NOINLINE void StoredProperties::Clear() {
// @@protoc_insertion_point(message_clear_start:astarteplatform.msghub.StoredProperties)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.interface_properties_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StoredProperties::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StoredProperties& this_ = static_cast<const StoredProperties&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StoredProperties::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StoredProperties& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:astarteplatform.msghub.StoredProperties)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // map<string, .astarteplatform.msghub.InterfaceProperties> interface_properties = 1;
          if (!this_._internal_interface_properties().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::astarteplatform::msghub::InterfaceProperties>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::astarteplatform::msghub::InterfaceProperties,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_MESSAGE>;
            const auto& field = this_._internal_interface_properties();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "astarteplatform.msghub.StoredProperties.interface_properties");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "astarteplatform.msghub.StoredProperties.interface_properties");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:astarteplatform.msghub.StoredProperties)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StoredProperties::ByteSizeLong(const MessageLite& base) {
          const StoredProperties& this_ = static_cast<const StoredProperties&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StoredProperties::ByteSizeLong() const {
          const StoredProperties& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:astarteplatform.msghub.StoredProperties)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, .astarteplatform.msghub.InterfaceProperties> interface_properties = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_interface_properties_size());
              for (const auto& entry : this_._internal_interface_properties()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::astarteplatform::msghub::InterfaceProperties,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StoredProperties::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StoredProperties*>(&to_msg);
  auto& from = static_cast<const StoredProperties&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:astarteplatform.msghub.StoredProperties)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.interface_properties_.MergeFrom(from._impl_.interface_properties_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StoredProperties::CopyFrom(const StoredProperties& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:astarteplatform.msghub.StoredProperties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StoredProperties::InternalSwap(StoredProperties* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.interface_properties_.InternalSwap(&other->_impl_.interface_properties_);
}

::google::protobuf::Metadata StoredProperties::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StoredPropertiesFilter::_Internal {
 public:
  using HasBits =
      decltype(std::declval<StoredPropertiesFilter>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StoredPropertiesFilter, _impl_._has_bits_);
};

StoredPropertiesFilter::StoredPropertiesFilter(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:astarteplatform.msghub.StoredPropertiesFilter)
}
StoredPropertiesFilter::StoredPropertiesFilter(
    ::google::protobuf::Arena* arena, const StoredPropertiesFilter& from)
    : StoredPropertiesFilter(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE StoredPropertiesFilter::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void StoredPropertiesFilter::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ownership_ = {};
}
StoredPropertiesFilter::~StoredPropertiesFilter() {
  // @@protoc_insertion_point(destructor:astarteplatform.msghub.StoredPropertiesFilter)
  SharedDtor(*this);
}
inline void StoredPropertiesFilter::SharedDtor(MessageLite& self) {
  StoredPropertiesFilter& this_ = static_cast<StoredPropertiesFilter&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* StoredPropertiesFilter::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StoredPropertiesFilter(arena);
}
constexpr auto StoredPropertiesFilter::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StoredPropertiesFilter),
                                            alignof(StoredPropertiesFilter));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StoredPropertiesFilter::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StoredPropertiesFilter_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StoredPropertiesFilter::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StoredPropertiesFilter>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StoredPropertiesFilter::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StoredPropertiesFilter>(), &StoredPropertiesFilter::ByteSizeLong,
            &StoredPropertiesFilter::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StoredPropertiesFilter, _impl_._cached_size_),
        false,
    },
    &StoredPropertiesFilter::kDescriptorMethods,
    &descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StoredPropertiesFilter::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> StoredPropertiesFilter::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StoredPropertiesFilter, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::astarteplatform::msghub::StoredPropertiesFilter>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .astarteplatform.msghub.Ownership ownership = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StoredPropertiesFilter, _impl_.ownership_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(StoredPropertiesFilter, _impl_.ownership_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .astarteplatform.msghub.Ownership ownership = 1;
    {PROTOBUF_FIELD_OFFSET(StoredPropertiesFilter, _impl_.ownership_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void StoredPropertiesFilter::Clear() {
// @@protoc_insertion_point(message_clear_start:astarteplatform.msghub.StoredPropertiesFilter)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ownership_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StoredPropertiesFilter::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StoredPropertiesFilter& this_ = static_cast<const StoredPropertiesFilter&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StoredPropertiesFilter::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StoredPropertiesFilter& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:astarteplatform.msghub.StoredPropertiesFilter)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .astarteplatform.msghub.Ownership ownership = 1;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_ownership(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:astarteplatform.msghub.StoredPropertiesFilter)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StoredPropertiesFilter::ByteSizeLong(const MessageLite& base) {
          const StoredPropertiesFilter& this_ = static_cast<const StoredPropertiesFilter&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StoredPropertiesFilter::ByteSizeLong() const {
          const StoredPropertiesFilter& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:astarteplatform.msghub.StoredPropertiesFilter)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // optional .astarteplatform.msghub.Ownership ownership = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_ownership());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StoredPropertiesFilter::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StoredPropertiesFilter*>(&to_msg);
  auto& from = static_cast<const StoredPropertiesFilter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:astarteplatform.msghub.StoredPropertiesFilter)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.ownership_ = from._impl_.ownership_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StoredPropertiesFilter::CopyFrom(const StoredPropertiesFilter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:astarteplatform.msghub.StoredPropertiesFilter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StoredPropertiesFilter::InternalSwap(StoredPropertiesFilter* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.ownership_, other->_impl_.ownership_);
}

::google::protobuf::Metadata StoredPropertiesFilter::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PropertyIdentifier::_Internal {
 public:
};

PropertyIdentifier::PropertyIdentifier(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:astarteplatform.msghub.PropertyIdentifier)
}
inline PROTOBUF_NDEBUG_INLINE PropertyIdentifier::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::astarteplatform::msghub::PropertyIdentifier& from_msg)
      : interface_name_(arena, from.interface_name_),
        path_(arena, from.path_),
        _cached_size_{0} {}

PropertyIdentifier::PropertyIdentifier(
    ::google::protobuf::Arena* arena,
    const PropertyIdentifier& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PropertyIdentifier* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:astarteplatform.msghub.PropertyIdentifier)
}
inline PROTOBUF_NDEBUG_INLINE PropertyIdentifier::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : interface_name_(arena),
        path_(arena),
        _cached_size_{0} {}

inline void PropertyIdentifier::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PropertyIdentifier::~PropertyIdentifier() {
  // @@protoc_insertion_point(destructor:astarteplatform.msghub.PropertyIdentifier)
  SharedDtor(*this);
}
inline void PropertyIdentifier::SharedDtor(MessageLite& self) {
  PropertyIdentifier& this_ = static_cast<PropertyIdentifier&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.interface_name_.Destroy();
  this_._impl_.path_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PropertyIdentifier::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PropertyIdentifier(arena);
}
constexpr auto PropertyIdentifier::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PropertyIdentifier),
                                            alignof(PropertyIdentifier));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PropertyIdentifier::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PropertyIdentifier_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PropertyIdentifier::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PropertyIdentifier>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PropertyIdentifier::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PropertyIdentifier>(), &PropertyIdentifier::ByteSizeLong,
            &PropertyIdentifier::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PropertyIdentifier, _impl_._cached_size_),
        false,
    },
    &PropertyIdentifier::kDescriptorMethods,
    &descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PropertyIdentifier::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 68, 2> PropertyIdentifier::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::astarteplatform::msghub::PropertyIdentifier>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string path = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PropertyIdentifier, _impl_.path_)}},
    // string interface_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PropertyIdentifier, _impl_.interface_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string interface_name = 1;
    {PROTOBUF_FIELD_OFFSET(PropertyIdentifier, _impl_.interface_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string path = 2;
    {PROTOBUF_FIELD_OFFSET(PropertyIdentifier, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\51\16\4\0\0\0\0\0"
    "astarteplatform.msghub.PropertyIdentifier"
    "interface_name"
    "path"
  }},
};

PROTOBUF_NOINLINE void PropertyIdentifier::Clear() {
// @@protoc_insertion_point(message_clear_start:astarteplatform.msghub.PropertyIdentifier)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.interface_name_.ClearToEmpty();
  _impl_.path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PropertyIdentifier::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PropertyIdentifier& this_ = static_cast<const PropertyIdentifier&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PropertyIdentifier::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PropertyIdentifier& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:astarteplatform.msghub.PropertyIdentifier)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string interface_name = 1;
          if (!this_._internal_interface_name().empty()) {
            const std::string& _s = this_._internal_interface_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "astarteplatform.msghub.PropertyIdentifier.interface_name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string path = 2;
          if (!this_._internal_path().empty()) {
            const std::string& _s = this_._internal_path();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "astarteplatform.msghub.PropertyIdentifier.path");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:astarteplatform.msghub.PropertyIdentifier)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PropertyIdentifier::ByteSizeLong(const MessageLite& base) {
          const PropertyIdentifier& this_ = static_cast<const PropertyIdentifier&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PropertyIdentifier::ByteSizeLong() const {
          const PropertyIdentifier& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:astarteplatform.msghub.PropertyIdentifier)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string interface_name = 1;
            if (!this_._internal_interface_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_interface_name());
            }
            // string path = 2;
            if (!this_._internal_path().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_path());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PropertyIdentifier::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PropertyIdentifier*>(&to_msg);
  auto& from = static_cast<const PropertyIdentifier&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:astarteplatform.msghub.PropertyIdentifier)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_interface_name().empty()) {
    _this->_internal_set_interface_name(from._internal_interface_name());
  }
  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PropertyIdentifier::CopyFrom(const PropertyIdentifier& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:astarteplatform.msghub.PropertyIdentifier)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PropertyIdentifier::InternalSwap(PropertyIdentifier* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.interface_name_, &other->_impl_.interface_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
}

::google::protobuf::Metadata PropertyIdentifier::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace msghub
}  // namespace astarteplatform
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_astarteplatform_2fmsghub_2fproperty_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
