# This file is part of Astarte.
#
# Copyright 2023 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Code Generation

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
      - 'release-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  reuse:
    uses: ./.github/workflows/reuse-lint.yaml
  python-code-generation:
    needs: [ reuse ]
    uses: ./.github/workflows/python-code-generation.yaml
  rust-code-generation:
    needs: [ reuse ]
    uses: ./.github/workflows/rust-code-generation.yaml
  cpp-code-generation:
    needs: [ reuse ]
    uses: ./.github/workflows/cpp-code-generation.yaml
  check-codegen:
    needs: [ python-code-generation, rust-code-generation, cpp-code-generation ]
    uses: ./.github/workflows/check-code-generation.yaml
  rust-code-check:
    needs: [ check-codegen ]
    uses: ./.github/workflows/rust-check-code-generation.yaml
