# This file is part of Astarte.
#
# Copyright 2023 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: commit-codegen

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    name: Commit and push generated code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Commit the generated code
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./python
          git diff --staged --quiet || git commit -s -m "[Python]: Add generated code"
          mv ./rust-dist/astarteplatform.msghub.rs ./rust/astarte-message-hub-proto/src/astarteplatform.msghub.rs
          git add ./rust/astarte-message-hub-proto/src/astarteplatform.msghub.rs
          git diff --staged --quiet || git commit -s -m "[Rust]: Add generated code"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update generated code
          base: master
          labels: automated-pr
          branch: update-code-gen
          delete-branch: true
          signoff: true
